version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456aA!
      POSTGRES_DB: student_management
    ports:
      - "5433:5432"
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    environment:
      PYTHONPATH: "/app"
      TEST_DATABASE_URL: "postgresql://postgres:123456aA!@db:5432/test_student_management"
    depends_on:
      - db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
