pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                script {
                    def workspace = env.WORKSPACE.replace("\\", "/")
                    echo "Workspace: ${workspace}"
                }
                bat 'docker build -t lesson29_project -f lesson_29_docker/Dockerfile .'
            }
        }

        stage('Run Tests in Docker') {
            steps {
                script {
                    def workspace = env.WORKSPACE.replace("\\", "/")
                    echo "Workspace for tests: ${workspace}"
                }
                bat '''
                    docker run --rm
                    -v "${env.WORKSPACE}/tests:/app/tests"
                    -v "${env.WORKSPACE}/src:/app/src"
                    lesson29_project pytest --junitxml=results.xml
                '''
            }
        }
    }

    post {
        always {
            cleanWs()
        }
    }
}
