pipeline {
    agent any

    stages {
        stage('Checkout Code') {
            steps {
                // Pulling the code from repository
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                // Building a Docker image
                bat '''
                    docker build -t lesson29_project -f lesson_29_docker/Dockerfile .
                '''
            }
        }

        stage('Run Tests in Docker') {
            steps {
                // Replace backslashes with forward slashes to make it Docker compatible
                    def workspace = env.WORKSPACE.replace("\\", "/")
                    bat '''
                        docker run --rm \
                        -v "${workspace}/tests:/app/tests" \
                        -v "${workspace}/src:/app/src" \
                        lesson29_project pytest --junitxml=results.xml
                    '''
            }
        }

        stage('Publish Test Results') {
            steps {
                // Collecting test results
                junit 'results.xml'
            }
        }
    }
  post {
        always {
            cleanWs()
        }
    }
}
