header_logo = ".global-layout .app-wrapper header.header .header_inner .header_left a.header_logo"
header_garage = "nav a.btn.header-link.-active"
header_fuel_expenses = "a.btn.header-link.-active + a"
header_instructions = "nav a.btn.header-link:nth-of-type(3)"
header_user_photo = "img.icon-btn"
header_my_profile = "button#userNavDropdown"

header_my_profile_dropdown_menu = "nav.user-nav_menu"
header_my_profile_dropdown_menu_1 = "nav.user-nav_menu a:first-child"
header_my_profile_dropdown_menu_2 = "nav.user-nav_menu.dropdown-menu a[href='/panel/expenses']"
header_my_profile_dropdown_menu_3 = "nav.user-nav_menu.dropdown-menu a.dropdown-item:nth-of-type(3)"
header_my_profile_dropdown_menu_logout = "button.dropdown-item"

sidebar_menu_1 = "a.btn-sidebar[href='/panel/garage']"
sidebar_menu_1_icon = "span.icon-garage"
sidebar_menu_2 = "a.btn-sidebar[href='/panel/expenses']"
sidebar_menu_2_icon = "span.icon-fuel"
sidebar_menu_3 = "a.btn-sidebar[href='/panel/instructions'"
sidebar_menu_3_icon = "span.icon-instructions"
sidebar_menu_logout = "a.btn.btn-link.text-danger.btn-sidebar.sidebar_btn"
sidebar_menu_logout_icon = "span.icon-logout"

main_page_garage_h1 = "div.panel-page_heading h1"
main_page_garage_add_car_btn = "div.panel-page_heading button"
main_page_garage_img_car = "div.panel-page_content svg path"
main_page_garage_empty_msg = "p.h3.panel-empty_message"

footer_logo = ".footer_logo svg"
footer_item_left = "div.footer_item.-left p"
