header_logo = "//a[@class='header_logo']"
header_home = "//a[text()='Home']"
header_about = "//button[text()='About']"
header_contacts = "//button[text()='Contacts']"

header_guest_log_in = "//button[text()='Guest log in']"

header_btn_sign_in = "//button[text()='Sign In']"

modal_window_sign_in = "//ngb-modal-window//div[@class='modal-content']"
modal_header = "//ngb-modal-window//h4[contains(@class, 'modal-title') and contains(text(), 'Log in')]"
modal_close_btn = "//ngb-modal-window//button/span[@aria-hidden='true' and text()='×']"
modal_email_label = "//label[@for='signinEmail']"
modal_email_input = "//*[@id='signinEmail']"
modal_password_label = "//label[@for='signinPassword']"
modal_password_input = "//*[@id='signinPassword']"
modal_remember_label = "//label[@for='remember']"
modal_remember_checkbox = "//*[@id='remember']"
modal_registration_btn_link = "//ngb-modal-window//button[contains(@class, 'btn btn-link') and text()='Registration']"
modal_login_btn = "//ngb-modal-window//button[contains(@class, 'btn btn-primary') and text()='Login']"

contacts_header = "//h2[text()='Contacts']"
contacts_link_homepage = "//*[@href='https://ithillel.ua']"
contacts_mail_to = "//*[@href='mailto:developer@ithillel.ua']"
contacts_fb = "//div[@id='contactsSection']//a[contains(@class, 'socials_link') and contains(@href, 'facebook.com')]"
contacts_telegram = "//div[@id='contactsSection']//a[contains(@class, 'socials_link') and contains(@href, 't.me')]"
contacts_youtube = "//div[@id='contactsSection']//a[contains(@class, 'socials_link') and contains(@href, 'youtube')]"
contacts_insta = "//div[@id='contactsSection']//a[contains(@class, 'socials_link') and contains(@href, 'instagram')]"
contacts_linkedin = "//div[@id='contactsSection']//a[contains(@class, 'socials_link') and contains(@href, 'linkedin')]"
